---
swagger: "2.0"
info:
  description: "This is simple resource monitor which allows to view how much are\
    \ used all resources on all monitored hosts. Note that we use token authorization\
    \ with JWT so you need to provide `Authorization` header with `Bearer [TOKEN]`\
    \ value on each request. You will receive token from auth server on successful\
    \ sign-in or sign-on action. Make sure monitor uses selected auth server. Monitor\
    \ should handle CORS with pre-flight, allowing query each path by OPTIONS to get\
    \ CORS headers.\n"
  version: "0.5.1"
  title: "ResMon - distributed resources monitoring"
  contact:
    name: "MAD-Team"
    email: "tbajorek3@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "tbajorek.pl:4000"
tags:
- name: "hosts"
- name: "metrics"
- name: "measurements"
schemes:
- "http"
security:
- APIKeyHeader: []
paths:
  /metrics:
    get:
      tags:
      - "metrics"
      summary: "List of metrics"
      operationId: "get_metrics"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            description: "Metric model instance"
            items:
              $ref: "#/definitions/Metric"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "It indicates whether the response can be shared with resources\
                \ with the given origin"
            Access-Control-Allow-Headers:
              type: "string"
              description: "It is used in response to a preflight request to indicate\
                \ which HTTP headers can be used during the actual request"
            Access-Control-Allow-Methods:
              type: "string"
              description: "It specifies the method or methods allowed when accessing\
                \ the resource in response to a preflight request"
        401:
          description: "User is not authorized"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.metrics_controller"
  /measurements:
    get:
      tags:
      - "measurements"
      summary: "Selected measurements"
      operationId: "get_measurements"
      produces:
      - "application/json"
      parameters:
      - name: "start"
        in: "query"
        description: "ISO 8601 datetime format with 1s accuracy. Default value is\
          \ current time subtracted by 1 day"
        required: false
        type: "string"
        format: "date-time"
      - name: "end"
        in: "query"
        description: "ISO 8601 datetime format with 1s accuracy. Default value is\
          \ current time."
        required: false
        type: "string"
        format: "date-time"
      - name: "q"
        in: "query"
        description: "Filters out used metrics and hosts according to provided keys.\
          \ String needs to match the following schema: `KEY1:VAL1,KEY2:VAL2;KEY3:VAL4...`.\
          \ Comma is used to indicate `AND` operation while semicolon relates to `OR`.\
          \ When `VAL` paramater is wrapped into slashes then regex mode is activated.\
          \ For example when we query for `metric_id:cpu,os:/.*nix.*/;metric_id:cpu,os:/.*win.*/`\
          \ we should receive cpu metric measurements for hosts containing either\
          \ nix or win as substring in `os` metadata. Note that `AND` operation has\
          \ higher priority than `OR`. Allowed keys: `metric_id`, `description`, `complex`\
          \ (metric parameters) and all available host metadata fields. When not provided:\
          \ No filtering performed - all available metrics and hosts are taken"
        required: false
        type: "string"
      - name: "limit"
        in: "query"
        description: "Number of maximal amount of measurements given as a result of\
          \ the query"
        required: false
        type: "number"
      - name: "last"
        in: "query"
        description: "If it is set as `TRUE` then the only last measurement meeting\
          \ the criteria from `q` parameter is returned"
        required: false
        type: "boolean"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            description: "Measurement model instance"
            items:
              $ref: "#/definitions/Measurement"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "It indicates whether the response can be shared with resources\
                \ with the given origin"
            Access-Control-Allow-Headers:
              type: "string"
              description: "It is used in response to a preflight request to indicate\
                \ which HTTP headers can be used during the actual request"
            Access-Control-Allow-Methods:
              type: "string"
              description: "It specifies the method or methods allowed when accessing\
                \ the resource in response to a preflight request"
        400:
          description: "Bad request - error in extra parameters"
          schema:
            $ref: "#/definitions/Error"
        401:
          description: "User is not authorized"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.measurements_controller"
  /hosts:
    get:
      tags:
      - "hosts"
      summary: "Get list of hosts"
      operationId: "get_hosts"
      produces:
      - "application/json"
      parameters:
      - name: "q"
        in: "query"
        description: "Filters out used metrics and hosts according to provided keys.\
          \ String needs to match the following schema: `KEY1:VAL1,KEY2:VAL2;KEY3:VAL4...`.\
          \ Comma is used to indicate `AND` operation while semicolon relates to `OR`.\
          \ When `VAL` paramater is wrapped into slashes then regex mode is activated.\
          \ For example when we query for `metric_id:cpu,os:/.*nix.*/;metric_id:cpu,os:/.*win.*/`\
          \ we should receive cpu metric measurements for hosts containing either\
          \ nix or win as substring in `os` metadata. Note that `AND` operation has\
          \ higher priority than `OR`. Allowed keys: `metric_id`, `description`, `complex`\
          \ (metric parameters) and all available host metadata fields. When not provided:\
          \ No filtering performed - all available metrics and hosts are taken"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            description: "Hosts models"
            items:
              $ref: "#/definitions/Host"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "It indicates whether the response can be shared with resources\
                \ with the given origin"
            Access-Control-Allow-Headers:
              type: "string"
              description: "It is used in response to a preflight request to indicate\
                \ which HTTP headers can be used during the actual request"
            Access-Control-Allow-Methods:
              type: "string"
              description: "It specifies the method or methods allowed when accessing\
                \ the resource in response to a preflight request"
        400:
          description: "Bad request - error in extra parameters"
          schema:
            $ref: "#/definitions/Error"
        401:
          description: "User is not authorized"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.hosts_controller"
  /hosts/{hostname}/metrics:
    post:
      tags:
      - "hosts"
      summary: "Add complex metric"
      operationId: "post_metric"
      parameters:
      - name: "hostname"
        in: "path"
        description: "Target host (domain name)"
        required: true
        type: "string"
      - in: "body"
        name: "payload"
        description: "Complex mertic payload"
        required: true
        schema:
          $ref: "#/definitions/payload"
      responses:
        201:
          description: "metric_id of created complex metric"
          schema:
            $ref: "#/definitions/inline_response_201"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "It indicates whether the response can be shared with resources\
                \ with the given origin"
            Access-Control-Allow-Headers:
              type: "string"
              description: "It is used in response to a preflight request to indicate\
                \ which HTTP headers can be used during the actual request"
            Access-Control-Allow-Methods:
              type: "string"
              description: "It specifies the method or methods allowed when accessing\
                \ the resource in response to a preflight request"
        400:
          description: "Incorrect metric data"
          schema:
            $ref: "#/definitions/Error"
        401:
          description: "User is not authorized"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Unknown hostname or metric passed as `parent_id`"
          schema:
            $ref: "#/definitions/Error"
        409:
          description: "If metric already exists, you can't change any field of it"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.hosts_controller"
  /hosts/{hostname}/metrics/{metric_id}:
    delete:
      tags:
      - "hosts"
      summary: "Delete complex metric"
      operationId: "delete_metric"
      parameters:
      - name: "metric_id"
        in: "path"
        description: "Metric identyfier. It has the same form as `metric_id` field\
          \ of `Metric` model"
        required: true
        type: "string"
      - name: "hostname"
        in: "path"
        description: "Target host (domain name)"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties: {}
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "It indicates whether the response can be shared with resources\
                \ with the given origin"
            Access-Control-Allow-Headers:
              type: "string"
              description: "It is used in response to a preflight request to indicate\
                \ which HTTP headers can be used during the actual request"
            Access-Control-Allow-Methods:
              type: "string"
              description: "It specifies the method or methods allowed when accessing\
                \ the resource in response to a preflight request"
        401:
          description: "User is not authorized"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "You aren't a creator of complex metric"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Unknown metric or hostname"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.hosts_controller"
securityDefinitions:
  APIKeyHeader:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  Point:
    type: "object"
    properties:
      time:
        type: "string"
        format: "date-time"
        description: "ISO 8601 datetime format with 1s accuracy"
      value:
        type: "number"
        format: "double"
        description: "Numerical value corresponding to the metric unit"
    example:
      time: "2000-01-23T04:56:07.000+00:00"
      value: 0.80082819046101150206595775671303272247314453125
  Measurement:
    type: "object"
    properties:
      metric_id:
        type: "string"
        description: "Metric slug name e.g. `ram`, `cpu`"
      hostname:
        type: "string"
        description: "Target host (domain name)"
      data:
        type: "array"
        description: "Actual timeseries"
        items:
          $ref: "#/definitions/Point"
    description: "Measurement object with timeseries to show in line chart"
    example:
      metric_id: "metric_id"
      hostname: "hostname"
      data:
      - time: "2000-01-23T04:56:07.000+00:00"
        value: 0.80082819046101150206595775671303272247314453125
      - time: "2000-01-23T04:56:07.000+00:00"
        value: 0.80082819046101150206595775671303272247314453125
  Metric:
    type: "object"
    required:
    - "description"
    - "unit"
    properties:
      id:
        type: "string"
        description: "Metric slug name. For basic metrics this is e.g. `ram`, `cpu`.\
          \ For complex metrics this is concatenation produced as `cpx_{parent_id}_{moving_window_duration}_{interval}`"
      description:
        type: "string"
        description: "Detailed informations about metric"
      parent_id:
        type: "string"
        description: "Id of a metric on which is based the complex metric. For basic\
          \ metric this value is set as `null`."
      unit:
        type: "string"
        description: "String that should be appended to chart tooltip / legend eq.\
          \ `%` or `Mb`"
      moving_window_duration:
        type: "integer"
        description: "Duration of moving window in seconds"
      interval:
        type: "integer"
        description: "Number of seconds between each new point in produced series"
      removable:
        type: "boolean"
        description: "True if metric is owned by logged user"
      hosts:
        type: "array"
        description: "Array of hostnames"
        items:
          type: "string"
          description: "Host name"
    description: "Metric object, when complex = true then moving_window_duration,\
      \ interval and removable need to be provided"
    example:
      unit: "unit"
      parent_id: "parent_id"
      moving_window_duration: 0
      removable: true
      hosts:
      - "hosts"
      - "hosts"
      description: "description"
      interval: 6
      id: "id"
  Metadata:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "string"
        description: "Unique identifier / alias / slug"
      name:
        type: "string"
        description: "Detailed information about this metadata e.g. what kind of values\
          \ we should expect"
      value:
        type: "string"
        description: "Value, format or type depends of type but should be string in\
          \ general. It has `null` value when metadata value is not specified."
    description: "Host meta information"
    example:
      name: "name"
      id: "id"
      value: "value"
  Host:
    type: "object"
    required:
    - "hostname"
    - "metadata"
    - "metrics"
    properties:
      hostname:
        type: "string"
        description: "Domain name for host"
      metrics:
        type: "array"
        description: "Array of metrics (both complex and basic)"
        items:
          $ref: "#/definitions/Metric"
      metadata:
        type: "array"
        description: "Various host properties eg. os, unit specification"
        items:
          $ref: "#/definitions/Metadata"
    description: "Host object containing domain name, supported metrics and available\
      \ metadata (e.g. OS)"
    example:
      hostname: "hostname"
      metadata:
      - name: "name"
        id: "id"
        value: "value"
      - name: "name"
        id: "id"
        value: "value"
      metrics:
      - unit: "unit"
        parent_id: "parent_id"
        moving_window_duration: 0
        removable: true
        hosts:
        - "hosts"
        - "hosts"
        description: "description"
        interval: 6
        id: "id"
      - unit: "unit"
        parent_id: "parent_id"
        moving_window_duration: 0
        removable: true
        hosts:
        - "hosts"
        - "hosts"
        description: "description"
        interval: 6
        id: "id"
  Error:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
  payload:
    type: "object"
    required:
    - "description"
    - "interval"
    - "moving_window_duration"
    properties:
      description:
        type: "string"
        description: "Detailed informations about metric"
      parent_id:
        type: "string"
        description: "Id of a metric on which is based the complex metric"
      moving_window_duration:
        type: "integer"
        description: "Duration of moving window in seconds"
      interval:
        type: "integer"
        description: "Number of seconds between each new point in produced series"
  inline_response_201:
    properties:
      id:
        type: "string"
        description: "ID of metric, need to follow this convention: `cpx_{parent_id}_{moving_window_duration}_{interval}`"
      unit:
        type: "string"
        description: "Should be the same as in metric identified by parent_id parameter"
    example:
      unit: "unit"
      id: "id"
